spring:
  #  security:
  #    user:
  #      name: user
  #      password: password

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    show-sql: true
    hibernate:
      ddl-auto: update

okta:
  oauth2:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    issuer: https://${OKTA_DOMAIN}/oauth2/default
    redirect-uri: /authorization-code/callback